export const baseurl = "https://warm-springs-86808.herokuapp.com/api"
export const popularEndpoint = "/popular"
export const relatedEndPoint = "/related"
export const searchEndPoint = "/search"
export const listenEndPoint = "/listen"
export const downloadEndPoint = "/download"